import { Inter } from "next/font/google";
import "./globals.css";
import TestHeader from "./components/homepageComponents/TestHeader"
import Footer from "./components/homepageComponents/Footer";  

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EVENTURE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <TestHeader/>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
